kind: pipeline
type: docker
name: main

steps:
- name: build
  image: pfillion/drone-dind
  volumes:
  - name: docker_volume
    path: /var/run
  commands:
  - sleep 10 # give docker enough time to start
  - make build

- name: test
  image: pfillion/drone-dind
  volumes:
  - name: docker_volume
    path: /var/run
  commands:
  - make test

- name: docker-push
  image: pfillion/drone-dind
  volumes:
  - name: docker_volume
    path: /var/run
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
  - make docker-push

services:
- name: docker
  image: pfillion/drone-dind
  privileged: true
  network_mode: bridge
  volumes:
  - name: docker_volume
    path: /var/run

volumes:
- name: docker_volume
  temp: {}